version: "3.7"

services:
  nanos:
    # build: .
    image: ghcr.io/blooo-io/speculos
    volumes:
      - ./bin:/speculos/apps
      - ./src:/speculos/src1
      - ./lib:/speculos/src2
      - ./proto:/speculos/src3

    ports:
      - "1234:1234" # gdb
      - "5000:5000" # api
      - "40000:40000" # apdu

    environment:
      - GDB_DIRECTORY_LIST="/speculos/src1:/speculos/src2:/speculos/src3"

    command: "--model nanos apps/app.elf --display headless --apdu-port 40000 -d"
    # Add `--vnc-password "<password>"` for macos users to use built-in vnc client.